#!/usr/bin/env bash

echo "generating images..."

convert -background none -density "1200" -resize 16x16 "icon.svg" icon-16.png

convert -background none -density "1200" -resize 32x32 "icon.svg" icon-32.png

convert -background none -density "1200" -resize 48x48 "icon.svg" icon-48.png

convert -background none -density "1200" -resize 64x64 "icon.svg" icon-64.png

convert -background none -density "1200" -resize 96x96 "icon.svg" icon-96.png

convert -background none -density "1200" -resize 128x128 "icon.svg" icon-128.png

convert -background none -density "1200" -resize 256x256 "icon.svg" icon-256.png
